apiVersion: v1
kind: ConfigMap
metadata:
  name: log-forwarder
  namespace: {{ .Release.Namespace }}
  annotations:
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

    [INPUT]
        Name tail
        Path /var/log/containers/*_{{ .Release.Namespace }}_*.log
        Exclude_Path /var/log/containers/*{{ .Release.Namespace }}_log-forwarder*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        DB /var/log/fluentbit.db

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name             http
        Match            *
        Host             logs.opal.dev
        Port             443
        URI              /receiver/v1/http/${LOG_FORWARDING_KEY}
        Format           json_lines
        Json_date_key    timestamp
        Json_date_format iso8601
        tls        On
        tls.verify Off
