apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-forwarder
subjects:
  - kind: ServiceAccount
    name: log-forwarder
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
