apiVersion: extensions/v1
kind: Ingress
metadata:
  name: {{ include "opal-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kots.io/exclude: {{ .Values.ingress.alb | quote }}
    {{- if .Values.ingress.override }}
    {{- toYaml .Values.ingress.overrideAnnotations | nindent 4 }}
    {{- else }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.aws.certArn }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
  labels:
    app: {{ .Values.app }}
spec:
  rules:
    - http:
        paths:
          - path: /*
          - pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port: use-annotation
          - path: /*
          - pathType: Prefix
            backend:
              service:
                name: {{ include "opal-web.fullname" . }}
                port: {{ .Values.service.port }}
