apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opal-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_USER: {{ .Values.env.postgresUser | trim | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.env.postgresPassword | trim | b64enc }}
  DATABASE_ENCRYPTION_KEY: {{ .Values.env.databaseEncryptionKey | b64enc }}
  REDIS_PASSWORD: {{ .Values.env.redisPassword | trim | b64enc }}
  AUTH_TOKEN_ENCRYPTION_KEY: {{ .Values.env.authTokenEncryptionKey | b64enc }}
  AUTH0_MANAGEMENT_CLIENT_SECRET: {{ .Values.env.auth0ManagementClientSecret | b64enc }}
  SECURE_COOKIE_HASHKEY: {{ .Values.env.secureCookieHashkey | b64enc }}
  AUTH0_CLIENT_SECRET: {{ .Values.env.auth0ClientSecret | b64enc }}
  SENDGRID_API_KEY: {{ .Values.env.sendgridApiKey | b64enc }}
  SLACK_CLIENT_SECRET: {{ .Values.env.slackClientSecret | b64enc }}
  {{- if ne .Values.env.environment "on_prem" }}
  MERGE_API_KEY: {{ .Values.env.mergeApiKey | b64enc }}
  SLACK_SIGNING_SECRET: {{ .Values.env.slackSigningSecret | b64enc }}
  SENTRY_AUTH_TOKEN: {{ .Values.env.sentryAuthToken | b64enc }}
  DATABASE_ENCRYPTION_KMS_ARN: {{ .Values.aws.databaseEncryptionKmsArn | b64enc }}
  OPAL_API_ENCRYPTION_KMS_ARN: {{ .Values.aws.opalApiEncryptionKmsArn | b64enc }}
  UNIDOC_LICENSE_KEY: {{ .Values.env.unidocLicenseKey | b64enc }}
  {{- end }}
  {{- if eq .Values.env.environment "on_prem" }}
  OPAL_API_ENCRYPTION_KEY: {{ .Values.env.opalApiEncryptionKey | b64enc }}
  {{- end }}
  {{- if and (ne .Values.env.environment "prod") (ne .Values.env.environment "sandbox") }}
  SLACK_OAUTH_2_TOKEN: {{ .Values.env.slackOAuth2Token | b64enc }}
  GOOGLE_SERVICE_ACCOUNT_BASE_SIXTY_FOUR: {{ .Values.env.googleServiceAccountBaseSixtyFour | b64enc }}
  JIRA_API_TOKEN: {{ .Values.env.jiraApiToken | b64enc }}
  PAGERDUTY_API_TOKEN: {{ .Values.env.pagerdutyApiToken | b64enc }}
  LINEAR_API_KEY: {{ .Values.env.linearApiKey | b64enc }}
  {{- end }}
  {{- if eq .Values.env.environment "prod" }}
  OPAL_ON_PREM_API_KEY: {{ .Values.env.opalOnPremApiKey | b64enc }}
  {{- end }}
