apiVersion: v1
kind: Service
metadata:
  name: {{ include "opal-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app }} # Map any pod with label `app=opal` to this service
  type: {{ .Values.service.type }} # A port is opened on each node in your cluster via Kube proxy.
  ports: # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
