apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app }}
    tags.datadoghq.com/env: {{ .Values.env.environment }}
    tags.datadoghq.com/service: sync
    tags.datadoghq.com/version: {{ .Chart.AppVersion }}
spec:
  schedule: "*/30 * * * *"
  # startingDeadlineSeconds is the time window K8s is using to count the missed start times.
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Values.app }}
            tags.datadoghq.com/env: {{ .Values.env.environment }}
            tags.datadoghq.com/service: sync
            tags.datadoghq.com/version: {{ .Chart.AppVersion }}
        spec:
          containers:
          - name: sync
            image: {{ .Values.image.repository }}/opal-web_backend_self_hosted:{{.Chart.AppVersion}}
            env:
              - name: DD_SERVICE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/service']
              - name: DD_AGENT_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            envFrom:
              - configMapRef:
                  name: {{ include "opal-web.fullname" . }}
              - secretRef:
                  name: {{ include "opal-web.fullname" . }}
            command: ["sh", "-c", "--"]
            args: ["./sync"]
          restartPolicy: Never
