apiVersion: v1
kind: Secret
metadata:
  name: opal-vault-storage
  namespace: {{ .Release.Namespace }}
stringData:
  config.hcl: |
    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = "true"
    }
    storage "postgresql" {
      connection_url = "postgres://{{ .Values.env.postgresUser | trim }}:{{ .Values.env.postgresPassword | trim | urlquery }}@{{ .Values.env.postgresHost | trim }}:{{ .Values.env.postgresPort }}/{{ .Values.env.postgresDb | trim }}?sslmode=disable"
      ha_enabled = "false"
    }
